security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        in_memory: { memory: null }
        database_users:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: database_users
            form_login:
                login_path: login
                check_path: login
                default_target_path: 2fa
                always_use_default_target_path: true
            logout:
                path: logout
                target: logout_callback
            two_factor:
                auth_form_path: 2fa
                check_path: 2fa_check
                default_target_path: espace-pro
                always_use_default_target_path: true

    access_control:
        # - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/register$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/2fa$, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/espace-pro$, roles: IS_AUTHENTICATED_FULLY }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN