security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        # used to reload user from session & other features (e.g. switch_user)

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: login
                check_path: login
                default_target_path: 2fa
                enable_csrf: true
            logout:
                path: logout
                target: /

            two_factor:
                auth_form_path: 2fa
                check_path: 2fa_check
                default_target_path: espace_pro
                always_use_default_target_path: false
                multi_factor: true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/2fa, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/espace-pro, roles: ROLE_2FA_COMPLETE }
            # Deny access by default to all other paths
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10