version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app1
    restart: unless-stopped
    ports:
      - "8000:3000"
    volumes:
      - .:/var/www/html
    environment:
      DATABASE_URL: mysql://root:Diakitem1.@db:3306/forest_hill_2fa
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: symfony_db1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Diakitem1.
      MYSQL_DATABASE: forest_hill_2fa
      MYSQL_PASSWORD: Diakitem1.
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
